---
# Path to cache file to write the serialized Ruby object of your following list
cache_file: .cache
# Number of hours to cache the list of users you're following
cache_time: 48
twitter:
  consumer_key: ''
  consumer_secret: ''
  access_token: ''
  access_token_secret: ''
